import Head from 'next/head'
import Image from 'next/image'
import { Client } from '@notionhq/client'

const notion = new Client({ auth: process.env.NOTION_ACCESS_TOKEN })
const databaseId: string = process.env.NOTION_DATABASE as string

async function addItem(text: string) {
  try {
    const response = await notion.pages.create({
      parent: {database_id: databaseId},
      properties: {
        title: {
          title: [
            {
              'text': {
                'content': text
              }
            }
          ]
        }
      }
    })
    console.log(response)
  } catch (error) {
    console.error(error.body)
  }
}

addItem('notion api sample')

export default function Home() {
  return (
    <>
      <Head>
        <title>Notion API - Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      
    </>
  )
}
